spring:
  application:
    name: OOBLOG
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/hojinzei?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
server:
  port: 8081
logging:
  level:
    org.springframework.security: info
  path:
  file: rakuchin_hojinzei.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan}[%line]    %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
oauth2:
  grantType: password
  scope: api
  clientId: kbt
  secret: 123456

